services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: library_backend
    restart: unless-stopped
    ports:
      - "8000:8000" 
    env_file:
      - .env
    environment:
      - PORT=8000
      - NODE_ENV=production
      - MONGO_URI=${MONGO_URI}
    networks:
      - mern_network

networks:
  mern_network:
    driver: bridge
